### ISSUE TITLE
Question: Can I add your excellent schematic to Bit Preserve?

### ISSUE THREAD

**Issue by baldengineer** [hzeller/trs80-100-schematic#1]
I came across your schematic while repairing my Model 100. I host the[ Bit Preserve repo](https://github.com/baldengineer/bit-preserve) is dedicated to vintage computer schematics [in KiCad]. 

Would it be okay if I add your repo as a submodule?

I created a fork as an example:
https://github.com/baldengineer/bit-preserve/tree/add-model-100-submodule/Tandy-RS

If you are okay with this addition, I will push to main!

Thanks,
James

**Comment by hzeller** [comment]
Yes, please! I think having it as a submodule in your wonderful bit preserve repo will help keeping related schematics together and discoverable.

**Comment by hzeller** [comment]
Can be closed now: is in https://github.com/baldengineer/bit-preserve/tree/add-model-100-submodule/Tandy-RS
